name: build and test all

on:
  push:
  pull_request:

jobs:
  run-eslint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependencies
        run: |
          sudo apt install -y ninja-build
      - name: app build
        run: |
          make build
      - name: app test
        run: |
          make test
      - name: app dependencies
        run: |
          npm install -g typescript
          npm i --dev
      - name: app build
        run: |
          npm run build
      - name: app lint
        run: |
          npm run lint
      - name: app format check
        run: |
          npm run format-check
